version: '3.8'

services:
  djangoapp:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev
    networks:
      - mynetwork

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
